### ISSUE TITLE
Create the generator

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs-travis-to-heroku#2]
This generator should handle setting up an application that is already set up with `donejs-heroku` to use CD with travis.

This should add the following configuration to the `.travis.yml` file, being careful not to override any user configuration.

```
deploy:
  skip_cleanup: true
  provider: "heroku"
  app: <my-app>
```

Not sure how to get the `<my-app>`, possibly by calling the heroku cli, or possibly we should save this info some where.
